### ISSUE TITLE
Make it possible that OpenEthnographer code names can contain spaces

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#104]
When a code's name includes a space, OE interprets it as two codes. So, typing `my code`in the code field results in the annotation being coded with `my`and `code`. This is new, because in the database we still have things like `existing systems failure`.

**Comment by tanius** [comment]
When you reload the page where you created an annotation that was split into several multi-word tags as described in this issue, you will see that it was not stored in the database at all. The splitting into one-word tags is a client-side side effect of the fact that, right now, Open Ethnographer tags can't be created on the fly at all. Which is why nothing was saved when trying to tag with a tag name that does not exist.

This will be fixed in #105 "Allow creating Open Ethnographer tags on the fly" though. So, nothing left to do in this issue here. (Closing it.)

Note that it is still possible to create Open Ethnographer tags with spaces in them, via the "New Tag" button on https://edgeryders.eu/administration/annotator/tags.
