### ISSUE TITLE
Rename the Open Ethnographer "tag_id" field to "code_id"

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#119]
In the `/annotations.json` API endpoint the ethnographic code's name is referred to by a key called `tag_id`. This is confusing, because the word "tag" in Discourse is assigned to a different entity. We follow the ethnographer's convention of calling these entity "codes".  

Maybe there are other inconsistencies apart from this.

**Comment by tanius** [comment]
I was just going to report the same issue :smile: 

This was missed when [we renamed](https://github.com/edgeryders/discourse/issues/97#issuecomment-344906088) things from `tag_id` to `code_id` after the initial release of the API.

So, it should simply be also `code_id` instead of `tag_id` in the JSON response. The current inconsistency can be observed here quite nicely (accessible for our Discourse staff users only):

https://edgeryders.eu/administration/annotator/annotations.json?code_id=15

**Comment by albertocottica** [comment]
Closed.
