### ISSUE TITLE
Provide access to a user's admin API key via SSO provider

### ISSUE THREAD

**Issue by owengot** [edgeryders/discourse#238]
In a number of scenarios we would like functionality to let an existing user post to the platform on another page, by logging in first via SSO to communities.edgeryders.eu.

My understanding is that this would require the user's admin API key, which is not available through this login method.

It would be very useful to include the user's API key in a custom field through the SSO provider, so we can achieve this.

**Comment by tanius** [comment]
I have discussed this with Owen, and agree that storing the user's admin API key in a field on our SSO provider site (communities.edgeryders.eu) would be the most straightforward solution, and acceptable in terms of security. Because if somebody can log in via SSO provider, they can do whatever they want in the user's account anyway – give or take the user's admin API key. In any case, it's preferable to the Discourse User API mechanism, which is made for connecting external apps but results in a mad forwarding back and forth to authorize an external app.

For this to work, we would need:

1. A mechanism that generates an admin API key for a user and stores it into a custom field in the user's profile on communities.edgeryders.eu upon signup. Most of this mechanism is already implemented in the extensions we did for the post-to-Discourse functionality.

2. Making sure that the admin API key is not visible to other (non-staff) users when stored in a custom user profile field on a Discourse site.

3. A one-time run of commands or a script in Ruby console to generate admin API keys for existing edgeryders.eu users, and store them into custom fields on communities.edgeryders.eu.

4. A way to return the user's admin API key upon SSO login to the SSO provider (communities.edgeryders.eu). Ideally it would be part of the SSO provider's response on login. Alternatively, it can be supplied by the SSO provider when receiving a certain API call.

**Comment by tanius** [comment]
Fixed with the above commit now.

The API endpoint is called like this, after login to communities.edgeryders.eu:

```
https://communities.edgeryders.eu/multisite_account_api_key.json?hostname=example.com
```

I'm adding the detailed documentation to [our API manual](https://edgeryders.eu/t/-/7904#heading--4).
