### ISSUE TITLE
Local installation fails on migration

### ISSUE THREAD

**Issue by aerugo** [edgeryders/discourse#243]
I'm following [this guide](https://meta.discourse.org/t/beginners-guide-to-install-discourse-on-macos-for-development/15772) to install Discourse locally for testing and development.

When running the migrations according to the instructions (`RAILS_ENV=test bundle exec rake db:create db:migrate`), it breaks:

```
== 20190429180007 AddAnnotatorStoreTagNames: migrating ========================
-- create_table(:annotator_store_tag_names, {})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "annotator_store_tag_names" already exists

```

**Comment by aerugo** [comment]
@gdpelican, did you manage to set it up locally?

**Comment by gdpelican** [comment]
I did yes, although I do remember there being some fiddling with the annotator-store gem (although I believe it was a different issue than the one you've posted)

That's a real weird error because the table name referenced only appears once in the migrations, so not sure why it would exist already; you might try a `rake db:drop db:create` to see if running the migrations from scratch helps.

Failing that, putting a check in the migration like
```
create_table : annotator_store_tag_names  do |t|
  ...
end unless ActiveRecord::Base.connection.table_exists?('annotator_store_tag_names')
```

Will hackily get around the problem.

**Comment by damingo** [comment]
This is now resolved. [Renaming](https://github.com/edgeryders/discourse-annotator/issues/96 ) the "annotator_store-gem" to "discourse-annotator" required namespace changes (that were used in migrations) as well as renaming all tables. So it made sense to replace all previous migrations with just [one](https://github.com/edgeryders/discourse-annotator/blob/master/db/migrate/20211217163310_initialize_discourse_annotator.rb).
