### ISSUE TITLE
Magic logo switch! Let's always use the round logo pretty please?

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#33]
Here is what happens as I scroll down a topic:

# start at the top... 

![image](https://user-images.githubusercontent.com/1976806/28175926-ecdff77c-67f5-11e7-9b28-3c063ae5a7d9.png)

# ...going down...

![image](https://user-images.githubusercontent.com/1976806/28175978-126f02c6-67f6-11e7-98a6-81fd0e9d2d0f.png)

# ... and there it is! 

The round logo has replaced the rectangular one. 

I strongly recommend using the round one, more unobstrusive. Big logos get old fast. 

![image](https://user-images.githubusercontent.com/1976806/28176044-45e10cb2-67f6-11e7-865a-022c62ad28d6.png)

**Comment by tanius** [comment]
The problem is, the small round logo is "so unobtrusive", its hard to even read the text on it, or see the blue dot.

Not sure how we can make the round logo show larger while a user is still at the top of the page (its small size while scrolling down in a topic is fine, as it is unobtrusive).

The [Discourse demo site](https://try.discourse.org/t/61) shows another possible behaviour.

**Comment by albertocottica** [comment]
I just like very small logos. Plus, you can read "Edgeryders" on every URL.
I really would not worry.
