### ISSUE TITLE
Implement right-to-left text formatting for Arabic

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#34]
There probably is a way prepared in Discourse to format Arabic etc. text using right-to-left text direction (means, right aligned). Probably:

- In titles: Unicode "text direction change" characters in titles
- In topic body text: Ideally a button in the Markdown editor to change text direction (maybe there is a plugin for that). Otherwise, a CSS class with `text-direction:right-to-left` in it to add to content.

See: [test case to work with](https://discourse.edgeryders.eu/t/34).

Can be documented in a manual topic in the "Help & Feedback" category.

**Comment by damingo** [comment]
To automatically set the text-direction by means of a  javascript plugin ([bidiweb.js](https://github.com/hasenj/bidiweb)) turns out to be more complicated than expected. It works after a full page reload, but when content is dynamically inserted by Discourse the JS method to reformat the content is not always triggered, and there seems to be no easy way accomplish this.

What works is to wrap right-to-left text with `<div dir="rtl">...</div>`. 

To allow a user to change the text-direction by means of a button in the editor is not easy. See: https://meta.discourse.org/t/setting-input-direction-in-ui/60203

**Comment by tanius** [comment]
Remaining work (which we moved to the next milestone): There will be a button added to the editor that creates custom Markdown code around selected text, which will later be cooked to `<div dir="rtl">…</div>` for proper display in the browser.

**Additional requirement:** The tag around Arabic text should be CSS-formattable to be able to adjust the font size of Arabic text compared to Latin letters, for better readability. So something like: `<div class="arabic-text" dir="rtl">…</div>`.

**Comment by damingo** [comment]
Button to choose right-to-left text formatting added to the editor.
