### ISSUE TITLE
Redirects for comments missing. 

### ISSUE THREAD

**Issue by jonathan-s** [edgeryders/discourse#50]
I took a look at graphryder and it seems like redirects are still missing for comments. Ie the link: https://edgeryders.eu/comment/28348#comment-28348 doesn't lead anywhere.

**Comment by albertocottica** [comment]
Thanks for the head up. This needs to be fixed in the context of GraphRyder, not here. Put up an issue on he GraphRyder repo: https://github.com/opencarecc/graph-ryder-dashboard/issues/26

**Comment by albertocottica** [comment]
Closed.

**Comment by tanius** [comment]
For reference, we created forwarder permalinks for all Drupal content URLs _except_ for Drupal groups and comments. Groups have no clear equivalents due to severe category tidy-up, and links to individual comments nearly always appear only within our own content (where we rewrote the links in the content to point to the equivalent Discourse comments now). Saves us ~20,000 entries in the permalink table …
