### ISSUE TITLE
Open API access

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#56]
I would like to start to learn using the APIs. Can someone open an access for me? 

As an exercise, I am going to alter my script so that [this](https://github.com/opencarecc/rapid-social-networks) works with the new platform.

Read-only access is Ok. Thanks, @tanius :-)

**Comment by tanius** [comment]
Since you are a moderator (and even admin) in Discourse, you can create an API key for yourself here:

Go to [Admin → Users → "alberto"](https://edgeryders.eu/admin/users/4/alberto), click "API Key → Generate".

Not sure how to utilize that key once you have it, but there are no permission and load restrictions attached to it. So, happy coding.
