### ISSUE TITLE
Make OpenCare content from the Drupal site identifiable

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#72]
## Problem

In the old site, we could assign nodes to more than one group. We used the group `op3ncare community` to hold OpenCare stuff (even though also other OpenCare stuff went through challenge response-type nodes)

Some of the nodes in `op3ncare community` belonged to more than one group. When that happened the import script assigned the topic corresponding to the node to the first of the groups. As a result, many of those topics ended up in categories other than OpenCare. 

But we need all of them into the OpenCare dataset. Almost all of them have already been coded by Amelia. 

## Solution

* OpenEthnographer will harvest the topics to code based on tags, not categories.
* At the same time, categories are handy for an intuitive grouping of project-related content and its findability. 
* Project categories are ephemeral: when the project ends, they are moved to being sub-categories of the `Finished Challenges` category or dissolved.

So:

1. Assign the tag `project-opencare` to all topics corresponding to the OpenCare project as defined by our JSON API in Drupal ([csv file with node ids](https://github.com/edgeryders/discourse/files/1201833/opencare_nodes.csv.zip))
1. Write a script to assign tags to entire categories. Unfortunately, sometimes subcategories are NOT meant to be coded: for example, the `OpenCare Research` category is *not* part of the OpenCare study, except for a few topics handpicked by Amelia and myself. The script needs to manage this. Heads up: I cannot find a documented `put` method to assign a tag to topics.

1. It should be possible for researchers to run this script, so that they get an up-to-date list of stuff to be coded (for ethnographers,via a manually assigned code like `to-code`) or real-time social networks (for network people). All this happens via call to APIs of type `tags/{tag}.json`.

**Comment by tanius** [comment]
The second and third step of the solution ("2. Write a script to assign tags to entire categories. … 3. It should be possible for researchers to run this script") seem to be reasonably fast possible with the existing Discourse bulk actions feature:

1. Go to a category's topic list page.
2. If it is a top-level category and you only want to exclude content from one or more sub-categories, select "none" in the sub-category dropdown.
3. Scroll until you see all posts on one page.
4. Click the button in the top left over the list of topics to show the selection options, then click "Select all".
5. Click the top-right wrench icon, choose "Append Tags".
6. Repeat for the other categories – usually <7 for a project, so still ok.

If this is to be automated at some point, maybe there is a Discourse auto-tagging plugin. Or otherwise, we would develop one. It would provide two added options in a category's settings screen, tab "Tags":

* "Tags that will be applied automatically to every topic in this category, including its sub-categories:"
* "Tags that will be applied automatically to every topic in this category, excluding its sub-categories:"

**Comment by tanius** [comment]
The first application of this is complete now, as @anuzement assigned the `ethno-opencare` tag to all relevant content missing it.

For the future, the tag only has to be added to new topics in the categories, which is a 5 min admin action every few weeks before progressing with coding, using the instructions from [my comment above](#issuecomment-324490996). So I don't see a need for further automation here.
