### ISSUE TITLE
Create a nice-looking blog using the blog tag and remove the blog category 

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#73]
https://edgeryders.eu/tags/blog.rss

**Comment by albertocottica** [comment]
Starting to feel the need for this...

**Comment by tanius** [comment]
Yes me too. Esp. the sorting by last actvity (of edits etc.) rather than by creation date in [the tag list](https://edgeryders.eu/tags/blog) is bad for a blog. But that's the blog right now.

The "Blog" category has already been removed btw. Everything in there has been tagged by project in addition to the `blog` tag, and then it was sorted into our other categories.

**Comment by albertocottica** [comment]
"by last activity" is totally unviable because Anu keeps tweaking old stuff that then jumps up in the notifs. My notifs are a total mess. The blog will be the same. We do not make it public until this is fixed.

**Comment by tanius** [comment]
> We do not make it public until this is fixed.

That would be a bit harsh … let's not raise the bar of QA too much compared to our Drupal days, or life becomes difficult :smile:

So, the blog was public all the way under "Company → Official Blog", but @damingo fixed the rest of the issue now and made it optically very nice-looking, with previews and all, and sort order descending by topic creation date and not by activity. [Have a look](https://edgeryders.eu/tags/blog?view=topic-preview).

As a side effect, the same type of view (with topic preview) can be applied to any tag now by adding the `?view=topic-preview` parameter ([example](https://edgeryders.eu/tags/collaboration-help?view=topic-preview)). Maybe that's useful in other places. (It does not work for categories, but that could be added quickly if there's a need.)

**Comment by albertocottica** [comment]
It's really nice, but the wide-and-short format for the pictures tends to create ugly effects. Scroll down from [the blog page](https://edgeryders.eu/tags/blog?view=topic-preview) to see what I mean...

**Comment by tanius** [comment]
> the wide-and-short format for the pictures tends to create ugly effects

Ah right I forgot to mention about this. I think the banner format was a side effect of a bug at first, but I liked it b/c it gives a teaser of the image while saving vertical space, plus it is responsive.

True about the ugly effects, but also I have a solution for that, will need @anuzement to apply it for past posts and to monitor future posts. In short, if adapting the first image is not possible, there's a way to put a an additional 690×150 px  image as first image so that it only shows in the blog list, not in the post:

    <img src="…" height="1" width="1" />

Will be documented in the manuals as well.
